### ISSUE TITLE
job does not start

### ISSUE THREAD

**Issue by petershaw** [kelektiv/node-cron#376] opened 2018-08-27 18:37 UTC
This job never starts: 

    var CronJob = require('cron').CronJob;
    const job = new CronJob('* * * * * *', function() {
        console.log('You will see this message every second');
    }, null, true, 'Europe/Berlin');

    job.start();

Any Ideas?

node: v6.9.1

**Comment by petershaw** [comment] 2018-08-27 18:39
After reinstalling node_modules it starts. hmmm.

**Comment by evilosa** [comment] 2018-08-27 18:59
I have the same problem

**Comment by jackfurr** [comment] 2018-08-27 19:57
I too experienced an issue where 5 different servers (docker) running a number of 'CronJob' intervals were setup, all of a sudden stopped working at 5PM PDT 2018-08-24 (2018-08-25 00:00 UTC).  

I rebuilt the docker container which re-installed cron npm and deployed but cronstill failed to execute.

Node: v8.11.4

**Comment by ncb000gt** [comment] 2018-08-27 20:00
Which version of node-cron are yall using? If you're using 1.4.0, upgrade. There was a bug that was fixed in 1.4.1 by GH-375.

Let us know if you're on the latest though. Thanks.

**Comment by evilosa** [comment] 2018-08-27 20:32
I tried to upgrade to the latest 1.4.1. It didn't work, then I tried to downgrade to 1.4.0 but it didn't help too. Downgrade to version 1.3.0 solved the problem.

**Comment by jodevsa** [comment] 2018-08-27 20:34
Can you  provide us with the cronString your trying to execute ?

*Best regards,*

*Subhi Al Hasan*

**Comment by jodevsa** [comment] 2018-08-27 20:34
Can you provide us with the cron string your trying to execute ?

**Comment by evilosa** [comment] 2018-08-27 20:35
```// Run elastic checker every 3 minutes
  new CronJob('0 */3 * * * *', elasticsearchChecker, null, true);

  // Run freezed subtasks checker every 3 minutes
  new CronJob('0 */3 * * * *', frozenSubtasksChecker, null, true);

  // Run completed stack tasks checker every 3 minutes
  new CronJob('0 */3 * * * *', completedTasksChecker, null, true);```

**Comment by evilosa** [comment] 2018-08-27 20:38
It worked half a year. I did not change anything in this part. We had this problem after build a fresh container with a latest _cron_ version.

**Comment by evilosa** [comment] 2018-08-27 20:40
If it will be useful - I changed the version to 1.3.1 now. It's working too.

**Comment by petershaw** [comment] 2018-08-27 20:41
I can not reproduce the behaviour i posted. Strange. Deploy project next Friday. I'll cross my fingers.

**Comment by evilosa** [comment] 2018-08-27 20:45
I have the same behaviour on node v9.0.0, v9.11.2, v10.8.0. 
I using MacOs High Sierra 10.13.6

**Comment by ncb000gt** [comment] 2018-08-27 20:51
@evilosa using 1.4.1 I assume?

**Comment by evilosa** [comment] 2018-08-27 20:52
@ncb000gt Yes

**Comment by ncb000gt** [comment] 2018-08-27 20:52
Ok. Thanks.

**Comment by evilosa** [comment] 2018-08-27 20:54
@ncb000gt In production we using the Ubuntu 14.04, it doesn't work there too.

**Comment by jodevsa** [comment] 2018-08-27 20:59
Can't really reproduce  it, can you re-check the version with `npm show cron version`

this is firing every 3rd minute
`var CronJob = require('./cron').CronJob;
const job = new CronJob('0 */3 * * * *', function() {
    console.log('You will see this every 3rd min');
}, null, true);
job.start();
`

**Comment by ncb000gt** [comment] 2018-08-27 21:02
@jackfurr can you also check this ^ thanks!

**Comment by jodevsa** [comment] 2018-08-27 21:05
If possible  try checking version of package.json inside node_modules, ie: `cat node_modules/cron/package.json |grep cron`

**Comment by ncb000gt** [comment] 2018-08-27 21:07
Also, and likely more important, in `package-lock.json`, especially if you're using `*`.

**Comment by jodevsa** [comment] 2018-08-27 21:14
BTW, re-installing won't update  your packages.
execute `npm update` to update all your packages and `npm update cron` to only update cron.

**Comment by evilosa** [comment] 2018-08-27 21:25
I using the yarn v1.9.4. 
Answer from `yarn list cron` - `cron@1.4.1`

**Comment by evilosa** [comment] 2018-08-27 21:34
I test it again with version 1.4.1. Everything works with it. The problem was related to v1.4.0. Sorry :)

**Comment by evilosa** [comment] 2018-08-27 21:35
<img width="516" alt="screen shot 2018-08-28 at 00 35 27" src="https://user-images.githubusercontent.com/13976639/44687594-4c60f000-aa5a-11e8-9fe0-89719f70fa19.png">

**Comment by ncb000gt** [comment] 2018-08-27 22:28
@evilosa Awesome! Glad to hear it!

**Comment by ncb000gt** [comment] 2018-08-28 12:04
Ok. I'm going to close this ticket given that upgrading seems to resolve the issues noticed.

**Closed by ncb000gt** 2018-08-28 12:04 UTC
