### ISSUE TITLE
Can't create schedule with 30 or 31 day of every month

### ISSUE THREAD

**Issue by kzmkv** [kelektiv/node-cron#210] opened 2016-01-17 22:52 UTC
I'm trying to create a new job which should run every 30 or 31st day of month. Although cron strings like 
`'10 10 31 * *'`, `'0 10 10 31 * *'` or `'* 10 10 30 * *'` seem to be correct, I get exception `Month '1' is limited to '29' days.` which pushes me to explicitly specify months that have 30 or 31 days.
My proposal is not to reject cron strings that have at least one correct date in future.

**Comment by ultimate-tester** [comment] 2016-08-09 14:22
How does `0 0 3 L * ?` work for you?

**Comment by kdschaffe** [comment] 2016-09-14 19:59
Not sure if it's implied but will this also include something like `L-10`?

**Comment by ncb000gt** [comment] 2016-10-07 01:03
The issue described in the OP shouldn't happen. I'm looking into it now. Thanks.

@ultimate-tester and @kdschaffe right now the `L` notation doesn't work, it isn't implemented as this isn't a part of standard cron. However, the feature would be useful and I have a separate branch where I was doing work on this stuff. It has been a while since I worked more on it. I might check around for some other parsers to see if this can be easily implemented.

**Comment by ncb000gt** [comment] 2016-10-07 01:15
@kzmkv I changed the functionality to warn instead of throw. This is less opinionated about how it should be and will let the code still fire. The problem is obviously that creating a job with this will not run "reliably" but at least there will be warnings in the console now.

I'm going to keep this open given my attempts at the `L` style syntax.

**Comment by michaelparamon** [comment] 2017-09-15 06:51
hi @ncb000gt , is this feature already working?

**Comment by pincheira** [comment] 2018-07-20 16:42
Using the ```L``` alias is not supported as of July 20th 2018, but you can always just do it on the 1st day of the month, with the earliest timezone in the world. At least that works for my case.
```javascript
const earliestTimezone = 'Pacific/Kiritimati';
const firstDayOfTheMonth = '0 0 1 * *'; // at 00:00
const job = new CronJob({
  cronTime: firstDayOfTheMonth,
  onTick: myFunctionToBeRun,
  start: true,
  timeZone: earliestTimezone
});
```

**Comment by ncb000gt** [comment] 2018-08-04 03:47
I'd love to implement `L` but I need time and I'm sorely lacking in it. Thanks for that perspective @pincheira! Maybe someday this module can grow up. ;D

Closing due to age. Can create a new ticket if it comes up again.

**Closed by ncb000gt** 2018-08-04 03:47 UTC

**Comment by haifahrul** [comment] 2019-07-01 13:39
Maybe you can use the logic here. You can use package momentJS.


```JS
var CronJob = require('cron').CronJob;
var moment = require('moment');

new CronJob('* * * * * *', function() {
  console.log('You will see this message every second');

  if (isLastDayOfMonth()) {
    doSomeStuff()
  }
}, null, true, 'America/Los_Angeles');

function isLastDayOfMonth(){
  const currentDay  =  moment().format('YYYY-MM-DD');
  const lastDayOfCurrentMonth  =  moment(date).endOf('month').format('YYYY-MM-DD');

  if (currentDate === lastDayOfCurrentMonth) {
    return true;
  } else {
    return false;
  }
}

function doSomeStuff(){
  // your task here.
}
```
