### ISSUE TITLE
day of the week. one week a month(syntax question)

### ISSUE THREAD

**Issue by pvcon13** [kelektiv/node-cron#494] opened 2020-05-03 15:43 UTC
Thank you for this framework :)
Does this syntax work (seem to getting a parsing error)

45 23 ? 3,6,9,12 6#3

Meaning at 11: 45 ( I set the time zone)  on a quarterly basis on Saturday night where its the third Saturday on that month.

Basically I have a dev and a staging and a production system in the cloud and I want quarterly updates to run all Sunday early morning with each of the three clouds being updated a different week. 

Would be fine if I could just fires to be the first Sunday of the month and use different months. 

Do you support the # syntax? The routine is loading 10 plus hours of materials from a remote site and the db is really not fully online during that update.

If I have the syntax wrong please LMK. 
Alternatively suggestions are welcome.
thanks again for this, its a god send.

ps Alternatively: I notice you can pass in a date ( I assume with a timezone), but does that support an array of dates (like four days a year as I described above? If so that would work as well

**Comment by ncb000gt** [comment] 2020-05-03 16:54
Hi. This syntax isn't currently supported, nor is a n array of dates. I've been working towards supported expanded Cron syntax but am super busy with other things so little time to dedicate to it. I would definitely review a PR for it if someone can get to it before me.

The array bit is a little tricky, but I could try to think about how that might work. Might be faster to implement.

**Comment by t0lik** [comment] 2021-08-25 12:39
It would be great to support nth Suday of a month with `#n` notation. Also I failed to use 7 as Sunday you support only 0 as Sunday meanwhile https://crontab.guru/ supports 0 and 7 as Sunday.

**Comment by intcreator** [comment] 2023-03-18 02:40
going to close this for now as working as intended. as part of v4 I want to more closely align with Linux cron syntax, such as supporting 0 and 7 for Sunday and 1-12 for months so there are fewer gotchas but I want to tighten up v3 a bit more (specifically daylight savings issues and a potential fix for infinite loops). once we have a solid v4 I can look into extended cron syntax. for now I'll look at PRs for it but it's not the highest priority otherwise

**Closed by intcreator** 2023-03-18 02:40 UTC
