### ISSUE TITLE
Cron doesn't run after 15 minutes of running every 2 minutes

### ISSUE THREAD

**Issue by Cyberuben** [kelektiv/node-cron#231] opened 2016-05-12 11:28 UTC
I just had my application running for 15 minutes. I've had the same problem a few times already, where the cron simply stops executing. I do not have a function calling it to a stop anywhere, no infinite loops or whatsoever, so I don't think this could be the problem. I'm using the following code:

```
new cron("0 */2 * * * *", functionToExecute, null, true);
```

The function that is executed has a `console.log` to let me know it finished executing, this is printed every time, so I know it reaches the end of the function. What could the problem here be?

**Comment by frabbit** [comment] 2016-05-18 10:23
same problem for me, after a lot of bugfixing sessions i finally switched to https://github.com/merencia/node-cron and it works very well so far.

**Comment by ncb000gt** [comment] 2016-10-07 01:34
Sorry for the delay here. I've been able to leave test code open over night, testing DST stuff in the past, and everything ran as expected. I'm not entirely sure what would cause this to stop functioning- I can try speculating though.

 * If the "next time" was in the past, it seems unlikely that would be the case, but the `stop` will be called if this is the case.
 * If you are trying to call `setTime` that could cause some issues as it will stop the job from running, but I would expect you ruled that out.

I'm not sure if you're still experiencing this issue, but if so, can you start by looking at the next time, `timeout`, https://github.com/ncb000gt/node-cron/blob/master/lib/cron.js#L445.

Thanks.

**Comment by chiarishow** [comment] 2016-10-18 12:59
In my case the issue is NOT present in node 0.10 but only in node 4.x and later (6.x). If this can help someone.

**Comment by ncb000gt** [comment] 2018-08-04 03:57
Closing due to age. We can create a new ticket if still an issue.

**Closed by ncb000gt** 2018-08-04 03:57 UTC

**Comment by sheerlox** [comment] 2025-02-23 14:25
This issue is superseded by #962, which regroups similar issues and includes a general bug description, root cause analysis, reproduction instructions, and a proposed fix.

Please join the discussion and share any thoughts or concerns you may have before we go about implementing the proposed solution.
