### ISSUE TITLE
Midnight problem

### ISSUE THREAD

**Issue by TeodorKolev** [kelektiv/node-cron#400] opened 2019-01-30 17:02 UTC
Everything works fine till midnight. Then cron job begin to produce timeout requests. Server time is set to UTC. I have also tried with different timezones specified, or without timezone. Same error results. Socket hang up on my requests after midnight.. Every cron tick after midnight is fired with couple of minutes delay and it's http inner method response produce `TimeoutError: ResourceRequest timed out.` Does anyone has any idea why it breaks after 00:00?
```
const createCronJob = passedFunction =>
  new CronJob('00,10,20,30,40,50 * * * *', () => {
    return passedFunction();
  }, null, true, 'UTC');
```

node-cron version: 1.6

**Comment by ncb000gt** [comment] 2019-02-09 21:53
@TeodorKolev Hi, I just want to make sure I understand the problem you're having.

The cron runs normally and the `onTick` fires as expected until midnight because the `onTick` doesn't fire immediately at midnight the way you expected, but instead is delayed?

**Comment by TeodorKolev** [comment] 2019-02-09 21:59
@ncb000gt exactly

**Comment by ncb000gt** [comment] 2019-02-09 22:13
I setup a test that _should_ exemplify the issue you noted and it seems to pass fine. Locally. Obviously, it's a test and not the real env...so, I also ran a test by changing my machine time to 11:59:50, and the cron triggered when expected.

```
	it.only('should trigger onTick at midnight', function() {
		var c = 0;
		var d = new Date('12/31/2014');
		d.setSeconds(59);
		d.setMinutes(59);
		d.setHours(23);
		var clock = sinon.useFakeTimers(d.getTime());

		var job = new cron.CronJob({
			cronTime: '00 * * * * *',
			onTick: function() {
				c++;
			},
			start: true,
			timeZone: 'UTC'
		});

		clock.tick(1000); // move clock 1 second
		expect(c).to.eql(1);

		clock.restore();
		job.stop();
		expect(c).to.eql(1);
	});
```
<img width="690" alt="screen shot 2019-02-10 at 12 00 19 am" src="https://user-images.githubusercontent.com/62615/52526885-9434a600-2c8d-11e9-85ae-62d81f86db42.png">

So, I have a couple of questions.

Is it possible that the endpoint you're trying to hit is doing something at midnight? I've known places to put an automatic restart into systems for one reason or another, but this might be the reason for the delay and subsequent timeout you're seeing.

Did you add any logging to the beginning of your onTick callback or the module itself to see when the onTick itself actually fires vs the timeout response?

Let me know. Hopefully this is helpful, and I'm going to commit the test for tracking purposes.

**Comment by nilsd** [comment] 2019-09-21 17:56
Maybe related? I have this job setup:

```
new CronJob('0 12 * * 0', function() {
    tryRunReportJob();
}, null, true, 'Europe/Stockholm');
```

The job runs at 12:00 local time every Sunday, works fine. But every night at 00.00 UTC my app crashes and restarts (forever-service). I'm not sure how to catch the error or where to even start looking.

**Comment by intcreator** [comment] 2023-02-23 03:26
this issue is [described in a passing test](https://github.com/kelektiv/node-cron/blob/master/tests/cron.test.js#L714) so I'm going to close it for now. feel free to reopen it if you're still experiencing this issue

**Closed by intcreator** 2023-02-23 03:26 UTC

**Comment by Suryapratapsoniigt** [comment] 2024-05-16 03:51
Everything works  except mid-night cron. Even I have tried with timezone but it is not working. 

```
cron.schedule('0 0 * * *', async() => {
        try {
               console.log('logic')
        } catch (error) {
            console.error('Error occurred:', error);
        } 
    }, {
        scheduled : true,
        timezone: 'Asia/Kolkata' 
    }); 
```

**Comment by sheerlox** [comment] 2024-05-16 10:11
Issue confirmed. The test that was supposed to cover that didn't use the correct cron pattern. Working on it: https://github.com/kelektiv/node-cron/pull/884

**Comment by sheerlox** [comment] 2024-05-16 10:30
Actually, false alert: my machine is UTC+2 and the test had a discrepancy between the clock time and the timezone provided.

After fixing (https://github.com/kelektiv/node-cron/pull/884/commits/3428cacfa90e7d81c8da01c9abdd0223148d6f2a), the test passes as expected.

@Suryapratapsoniigt you're actually using https://github.com/node-cron/node-cron, which is known for being buggy and is unmaintained.

This repository does share the same name, but our package on npm is `cron`, not `node-cron`. Feel free to switch to `cron` :smile:
