### ISSUE TITLE
How to stop cron on command

### ISSUE THREAD

**Issue by paulbraam** [kelektiv/node-cron#488] opened 2020-04-21 08:33 UTC
Hi,

I'm creating a Telegram bot and I would like the cron job to stop on command.

Here is the code I used, but it doesn't work:

```
const CronJob = require('cron').CronJob;

bot.command('launch', (ctx) => {
  const job = new CronJob('*/5 * * * * *', function() {
    bot.telegram.sendMessage(ctx.chat.id, 'Hello World');
  }, null, true, 'America/Los_Angeles');
  job.start();
  if (ctx.message.text == '/stop') {
    job.stop();
  };
})
```
Can you please suggest what I'm doing wrong?
Thanks.

**Comment by intcreator** [comment] 2023-02-18 07:12
I think this is out of scope of node-cron. just a guess here, but it looks like you're starting a new cron job every time the `launch` command is sent and then immediately stopping it if the command text has `/stop` in it...but I'm not familiar with Telegram bots so I'm not sure.

going to close as off topic for now. if you can reproduce the issue without the bot code feel free to reopen

**Closed by intcreator** 2023-02-18 07:12 UTC
