### ISSUE TITLE
cron reached maximum iterations.

### ISSUE THREAD

**Issue by praepoke** [kelektiv/node-cron#414] opened 2019-03-30 15:09 UTC
30 Mar 02:00:00 - [red] Uncaught Exception:
30 Mar 02:00:00 - Error: Something went wrong. cron reached maximum iterations.
Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
Time Zone: "" - Cron String: 0 0 2 * * * - UTC offset: +02:00 - current Date: Sat Mar 30 2019 02:00:00 GMT+0100
    at CronTime._getNextDateFrom (/usr/local/lib/node_modules/node-red/node_modules/cron/lib/cron.js:243:12)
    at CronTime.sendAt (/usr/local/lib/node_modules/node-red/node_modules/cron/lib/cron.js:151:17)
    at CronTime.getTimeout (/usr/local/lib/node_modules/node-red/node_modules/cron/lib/cron.js:170:29)
    at CronJob.start (/usr/local/lib/node_modules/node-red/node_modules/cron/lib/cron.js:561:31)
    at Timeout.callbackWrapper [as _onTimeout] (/usr/local/lib/node_modules/node-red/node_modules/cron/lib/cron.js:613:29)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)

**Comment by ncb000gt** [comment] 2019-03-30 15:26
Which version of the module are you using?

**Comment by jasonpet** [comment] 2019-03-30 15:52
I am also running into this

**Comment by praepoke** [comment] 2019-03-30 16:46
thanks

**Comment by ncb000gt** [comment] 2019-03-30 16:53
@jasonpet @praepoke the module is at version 1.7.0. Try upgrading, We ran into this when the US went through DST and there was a fix specifically for this inside that version. Let me know if you still see it after that. Thanks!

**Comment by jasonpet** [comment] 2019-03-30 18:29
@ncb000gt - looks like the issue is fixed with 1.7.0.  Thank you.

**Comment by ncb000gt** [comment] 2019-03-30 18:35
That's great to hear! Thanks for letting me know. I'll close this out.

**Closed by ncb000gt** 2019-03-30 18:35 UTC

**Comment by ncb000gt** [comment] 2019-03-30 18:37
For reference, the issue was resolved in GH-408.
