### ISSUE TITLE
Mac OSX Node Webkit random execution

### ISSUE THREAD

**Issue by rodrigoreyes79** [kelektiv/node-cron#177] opened 2015-06-25 22:08 UTC
I have the following code in a Node Webkit app:

``` javascript
    new CronJob('0 0 8-18 * * 1-5', function(){
        vm.onPin();
        vm.focus();
    }, null, true, "America/Guayaquil");
```

It should execute the provided function at 0 secs 0 minutes, but it is executing it randomly missing several hours. I am running Node Webkit under Mac OSX (Yosemite)

**Comment by weisjohn** [comment] 2015-08-19 22:58
@rodrigoreyes79 are you ever seeing your jobs executing wildly in rapid succession?  Like 5 times in a row instead of just once?

**Comment by rodrigoreyes79** [comment] 2015-08-19 23:00
No, not really. Just runs randomly instead of using the cron expression.

R

**Comment by weisjohn** [comment] 2015-08-28 15:42
@rodrigoreyes79 I found out what my issue was, I was accidentally setting my job to run every second (first character was `*`) and I just needed every minute. 

It's working fine for me now inside nw.js.

**Comment by rodrigoreyes79** [comment] 2015-08-28 16:04
John

In my case, I am only running this every hour and I leave the app running
for a long time in the background. My problem persists as of today.

Rodrigo

2015-08-28 10:42 GMT-05:00 John Weis <notifications@github.com>:

**Comment by IharKrasnik** [comment] 2015-09-16 10:27
Have a similar issue, but only after computer returns from sleep (reproduced on OS X and Ubuntu)

**Comment by ncb000gt** [comment] 2015-10-24 17:53
@rodrigoreyes79 Are you seeing this with sleeps as @IharKrasnik is?

I could definitely see sleeps causing problems...not entirely sure how to resolve that with the existing implementation. The implementation uses `setTimeout()` and doesn't fire unless that timeout is reached. Seems to me that doing a second based interval could get costly which is part of why we moved away from it (and it also has the same issues since we were setting the interval based on the passed in cron syntax).

To fix this we'd need to either hook into some system calls  or have the cron system running with `setInterval` that verified things before running which, after enough checks will be too expensive and take too many cycles to execute.

I don't use node-webkit so I'd be happy to review/accept a PR for a fix for this if you guys come up with one.

**Comment by weisjohn** [comment] 2015-10-29 17:02
@ncb000gt just to be clear, I don't have this issue anymore. For me, it actually was a code issue.

**Closed** 2018-08-04 03:25 UTC
