### ISSUE TITLE
Cron killed itself on reaching max iterations.

### ISSUE THREAD

**Issue by bharathrao** [kelektiv/node-cron#507] opened 2020-06-26 19:20 UTC
Error: Something went wrong. cron reached maximum iterations.
Please open an issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
Time Zone: "" - Cron String: 0,30 * - UTC offset: -04:00 - current Date: Fri Jun 26 2020 15:12:08 GMT-0400
at CronTime._getNextDateFrom (myapp/node_modules/cron/lib/cron.js:235:12)
at CronTime.sendAt (myapp/node_modules/cron/lib/cron.js:156:17)
at CronTime.getTimeout (myapp/node_modules/cron/lib/cron.js:175:29)
at CronJob.start (myapp/node_modules/cron/lib/cron.js:613:31)
at Timeout.callbackWrapper [as _onTimeout] (myapp/node_modules/cron/lib/cron.js:665:29)
at ontimeout (timers.js:436:11)
at tryOnTimeout (timers.js:300:5)
at listOnTimeout (timers.js:263:5)
at Timer.processTimers (timers.js:223:10)

**Comment by Bilonik** [comment] 2020-07-09 20:31
Same issue

**Comment by whatwewant** [comment] 2021-07-12 08:04
+1

**Comment by whatwewant** [comment] 2021-07-12 08:09
![image](https://user-images.githubusercontent.com/7463687/125252566-19bf5300-e32b-11eb-9287-945cb635139c.png)

I think it caused by something making node event queue stop

**Comment by intcreator** [comment] 2023-02-16 02:22
closing in favor of #467

**Closed by intcreator** 2023-02-16 02:22 UTC
