### ISSUE TITLE
Experiencing Memory leak with version 1.2.1

### ISSUE THREAD

**Issue by occasl** [kelektiv/node-cron#287] opened 2017-05-01 14:29 UTC
After experiencing high memory usage on my scheduler, I turned on New Relic monitoring for my cron job and notice that over a period of time (days), I'm experiencing a memory leak. I have my job running every 30 minutes and most times is a no-op because there are no records in the DB that meet the criteria to do something. Can you take a look and let me know what you think?  Just to be clear, this happens without New Relic monitoring too. I added it to get more details about what's happening.

Here's my code:

```
const MAX_THREADS = 5;
const JOB_INTERVAL_MINUTES = process.env.JOB_INTERVAL_MINUTES || 30; // run every 15 minutes
const WAIT_MINUTES = process.env.WAIT_MINUTES || 180; // make sure record is at least 3 hours old
const RUN_SCHEDULER = process.env.SCHEDULER_WELCOME_EMAILS || nconf.get("deliver-email") || false;

runJob();

// function to simulate async work
function runJob() {
  try {
    new CronJob('0 */' + JOB_INTERVAL_MINUTES + ' * * * *', function () {
      const transactionName = 'email-scheduler';
      let invokeTransaction = newrelic.createBackgroundTransaction(transactionName,
        function () {
          sendEmail(function (error) {
            log.info("Job completed; ending transaction.");
            newrelic.endTransaction();
          });
        });
      // start the transaction
      invokeTransaction();
    }, function () {
      log.info('Scheduler completed job.');
    }, RUN_SCHEDULER, "America/Los_Angeles");
  } catch (ex) {
    log.error("cron job pattern not valid");
  }
}

function sendEmail(callback) {
  log.info('Scheduler woke up to send emails (set to send every ' + JOB_INTERVAL_MINUTES + ' minutes)');
  mongo.findUsersSince(WAIT_MINUTES, function (err, result) {
    if (err) {
      log.error("Welcome emails could not be sent: " + err);
      callback(err);
    }
    if (result && result instanceof Array) {
      async.eachLimit(result, MAX_THREADS, function (user, cb) {
        // Check if email already sent
        if (!user.emailSent) {
          var recipient = {
            email: user.email
          };
          api.sendWelcomeEmail(recipient, function (err) {
            if (err) {
              log.error("Welcome email could not be sent for user: " + JSON.stringify(recipient) + " due to: " + err);
            } else {
              mongo.updateUser(user);
            }
            cb();
          });
        }
      }, function (err) {
        let num = result ? result.length : 0;
        if (err) {
          log.info("Scheduler completed sending " + num + " email(s) but with: " + err);
        } else {
          log.info("Scheduler completed sending " + num + " email(s)");
        }
        callback(null);
      });
    } else  {
        callback(null);
    }
  });
}
```

**Comment by zackiles** [comment] 2017-09-26 02:55
I also experience the same issue. I have confirmed it's not releasing memory properly of anything it allocates within an execution of the cron task. This means, the more memory you use in the `onTick()` function, the quicker it will leak memory. To test it, load a bunch of database documents, and do it every 10 seconds and watch your memory. increase. For me, it will eventually end up in a `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory` and the application will crash.

Also confirmed it has nothing to do with the underlying function being called, or how I'm initializing a cron job. It's definitely an issue with this library, and I'd strongly advise never using in this production. It's also present in every version of this package.

**Comment by F3L1X79** [comment] 2018-01-11 10:11
Same here, have a memory leak on version 1.3.0. I rollbacked on 1.1.1 and the leak disappeared...

**Comment by ncb000gt** [comment] 2018-08-16 12:51
I'm not sure exactly what you're seeing but if you are still having this issue and can isolate it to the cron module I'd be happy to dig in more. The fact that you're seeing event emitter messages makes me think this isn't a cron issue since we don't use listeners in the code. I'd be happy to revisit it though.

I'm going to close this for now, but we can keep chatting here or reopen if you get something more isolated. Thanks!

**Closed by ncb000gt** 2018-08-16 12:51 UTC
