### ISSUE TITLE
Error: Something went wrong. cron reached maximum iterations.

### ISSUE THREAD

**Issue by hasansungur** [kelektiv/node-cron#415] opened 2019-04-01 07:55 UTC
I have received from our cron project following logs ;
we would like to know how to avoid those future errors? 
"" - Cron String: 0 0 5 * * * - UTC offset: +01:00 - current Date: Sat Mar 30 2019 04:00:00 GMT+0000 at CronTime._getNextDateFrom (/var/app/current/node_modules/cron/lib/cron.js:243:12) at CronTime.sendAt (/var/app/current/node_modules/cron/lib/cron.js:151:17) at CronTime.getTimeout (/var/app/current/node_modules/cron/lib/cron.js:170:29) at CronJob.start (/var/app/current/node_modules/cron/lib/cron.js:561:31) at Timeout.callbackWrapper [as _onTimeout] (/var/app/current/node_modules/cron/lib/cron.js:613:29) at ontimeout (timers.js:471:11) at tryOnTimeout (timers.js:306:5) at Timer.listOnTimeout (timers.js:266:5)"

**Comment by matteodisabatino** [comment] 2019-04-01 10:02
Same issue here. My code is:

```javascript
const myJob = new CronJob({
  cronTime: '0 0 6 * * *',
  onTick: myOnTick,
  start: myCondition,
  timeZone: 'Europe/Rome'
})
```

I think, but I'm not sure, that it may depend by the fact that on March 31st at 02:00am summer time (or daylight time if you prefer) started.

**Comment by ncb000gt** [comment] 2019-04-01 11:15
Which version of the module are you on? The latest is 1.7.0. There was an issue that was resolved in GH-408.

Let me know if upgrading resolves your issue.

**Comment by matteodisabatino** [comment] 2019-04-01 11:17
I'm using 1.5.0. I'll try to upgrade but I don't know how to reproduce it.

**Comment by ncb000gt** [comment] 2019-04-01 11:30
You should be able to reproduce it if you can change the time on your machine or server. But if not this issue has been popping up as others run into DST so I'm pretty sure that's what you are seeing.

**Comment by hasansungur** [comment] 2019-04-01 12:35
I am using 1.5.1. Will try to upgrade and as soon as possible i will update this issue as well

**Comment by ncb000gt** [comment] 2019-04-23 18:58
@hasansungur @matteodisabatino Any update on this?

**Comment by ncb000gt** [comment] 2019-05-13 18:42
Closing due to time. But, we can reopen if it's not related to the stuff I mentioned.

**Closed** 2019-05-13 18:42 UTC
