### ISSUE TITLE
unable to run every x minutes

### ISSUE THREAD

**Issue by jomapps** [kelektiv/node-cron#540] opened 2020-12-01 21:16 UTC
Hi,
Thank you everyone involved for their contribution.

0 */10 * * * * is given in the example for cron to run every 10 min.

This runs every 10 min but for every second !!!
So it runs the function 60 times !! Then it waits 10 min and does that again.

Also tried following combinations without success:
* */10 * * * *
1-59 */10 * * * *

Can you advise?

Thanks 
TeaCii

**Comment by HeitorGonzaga** [comment] 2020-12-02 00:40
Hi.
I don't know if I understood your question correctly, but come on.

0 * / 10 * * * * causes the function to run every 10 minutes.

If you want it to be executed every second you must use * * * * * * as as example in  examples/is_job_running.js

**Comment by HeitorGonzaga** [comment] 2020-12-02 00:41
> Hi,
> Thank you everyone involved for their contribution.
> 
> 0 */10 * * * * is given in the example for cron to run every 10 min.
> 
> This runs every 10 min but for every second !!!
> So it runs the function 60 times !! Then it waits 10 min and does that again.
> 
> Also tried following combinations without success:
> 
> * */10 * * * *
>   1-59 */10 * * * *
> 
> Can you advise?
> 
> Thanks
> TeaCii

Hi.
I don't know if I understood your question correctly, but come on.

0 * / 10 * * * * causes the function to run every 10 minutes.

If you want it to be executed every second you must use * * * * * * as as example in examples/is_job_running.js

**Comment by jomapps** [comment] 2020-12-02 11:38
HI,
You understood it right. I want to run every 10 min. And 
0 */10 * * * *
Runs every 10 min but 60 times.
Rephrased, it runs 60 times every 10 min.

No I do not want it executed every second.
So something is obviously up.

**Comment by kaungyeehein** [comment] 2021-09-19 17:50
Dear @jomapps 
If you run every 10 minutes. Your cron expression is wrong. It should be `*/10 * * * *`
Check at https://crontab.guru/every-10-minutes

**Comment by M4FFS** [comment] 2022-05-06 07:22
@kaungyeehein that is incorrect, this library has an extra field for seconds which crontab guru does not account for. 

Every 10 minutes is `0 */10 * * * *`

**Comment by intcreator** [comment] 2023-03-23 18:04
closing as unable to reproduce

**Closed by intcreator** 2023-03-23 18:04 UTC
