### ISSUE TITLE
Could not find a declaration file for module 'luxon'

### ISSUE THREAD

**Issue by vajkayrene** [kelektiv/node-cron#688] opened 2023-08-16 10:07 UTC
### Description

The following error message is thrown from the cron module (using Typescript):

```
node_modules/cron/types/index.d.ts:11:26 - error TS7016: Could not find a declaration file for module 'luxon'. '/api/node_modules/luxon/build/node/luxon.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/luxon` if it exists or add a new declaration (.d.ts) file containing `declare module 'luxon';`
```

The issue is caused by a missing type definition for the luxon library. The [docs](https://github.com/moment/luxon/blob/master/docs/install.md#types) for the library states it should be installed as a developer dependency separately for typescript. 

### Screenshots

<img width="633" alt="Screenshot 2023-08-16 at 11 58 11" src="https://github.com/kelektiv/node-cron/assets/2177941/dc97ee74-4889-44d0-9207-7293c13e9d32">

**Comment by sheerlox** [comment] 2023-08-16 10:22
You're absolutely right! Typescript cached a version of `@types/luxon` on my machines, so I didn't notice that error, thank you for reporting the issue!

**Comment by vajkayrene** [comment] 2023-08-16 10:27
> You're absolutely right! Typescript cached a version of `@types/luxon` on my machines, so I didn't notice that error, thank you for reporting the issue!

Yes, I had the same issue. 😄  Typescript cached the library on my local machine and I was scratching my head for 30 minutes about why it fails on the CI/CD server.

**Comment by sheerlox** [comment] 2023-08-16 10:33
If we'd add `@types/luxon` to this project, it would need to be added to the regular `dependencies`, so it would be installed for all users (even JS ones). The issue is that the package size is `115 kB` while `cron` is only `59.2 kB`.
Would you find installing the `@types/cron` package in your development dependencies a good solution until we convert the library to TS? If so I'll update the README to include a section about this.

**Comment by sheerlox** [comment] 2023-08-16 10:35
On the other hand `luxon` is `4.06 MB` so I guess adding `115 kB` is not the end of the world

**Comment by vajkayrene** [comment] 2023-08-16 11:51
> If we'd add `@types/luxon` to this project, it would need to be added to the regular `dependencies`, so it would be installed for all users (even JS ones). The issue is that the package size is `115 kB` while `cron` is only `59.2 kB`. Would you find installing the `@types/cron` package in your development dependencies a good solution until we convert the library to TS? If so I'll update the README to include a section about this.

I tried to install `@types/cron`, but the fact is typescript still gives me the original issue. I was able to fix it by installing @types/luxon to my devDependecies.

**Comment by sheerlox** [comment] 2023-08-16 11:53
I'm sorry I made a mistake in my message, I meant `@types/luxon` :sweat:

**Comment by sheerlox** [comment] 2023-08-16 11:58
I've made a PR to add `@types/luxon` to our dependencies, it should be merged soon :) thanks for the heads up!

**Comment by vajkayrene** [comment] 2023-08-16 12:08
No problem, thanks for the quick fix!

**Closed** 2023-08-26 16:18 UTC
Labels: bug

**Comment by sheerlox** [comment] 2023-09-01 10:53
@SirAndrii thanks for reporting on this, let's track this here: https://github.com/kelektiv/node-cron/issues/692
