### ISSUE TITLE
cron reached maximum iterations 

### ISSUE THREAD

**Issue by 13pass** [kelektiv/node-cron#394] opened 2018-12-09 07:54 UTC
Time Zone: "" - Cron String: 0 0 6 29 11 6 - UTC offset: +01:00 - current Date: Sun Dec 09 2018 08:41:45 GMT+0100
using cron@1.5.1

The error is triggered by calling cron.nextDates(5).
```at CronTime._getNextDateFrom (node_modules/cron/lib/cron.js:243:12)
      at CronTime.sendAt (node_modules/cron/lib/cron.js:158:18)
      at CronJob.nextDates (node_modules/cron/lib/cron.js:553:24)
      at nextDates (test/next.cronJobs.test.js:51:20)
      at Object.showPlanning (test/next.cronJobs.test.js:71:7)```

**Comment by ncb000gt** [comment] 2018-12-09 19:11
Dupe of GH-393, closing here, responding on other ticket. Thanks!

**Closed by ncb000gt** 2018-12-09 19:11 UTC

**Comment by 13pass** [comment] 2018-12-11 21:02
Thanks @ncb000gt, it fixes much of the issues but now I sometimes reach the 5000 ms timeout when doing a lot of concurrent actions while using nextDate.

I guess it would be nice to have the possibility to set the timeout value as a parameter of nextDates.

Thanks again!
