### ISSUE TITLE
Cron function triggering multiple times

### ISSUE THREAD

**Issue by NareshKukreti12** [kelektiv/node-cron#605] opened 2022-04-18 05:53 UTC
### Description

I have followed the steps defined in the documentation. I have scheduled a cron that is triggering every morning at 10 AM. Though on the local server everything is running perfectly , but after deploying the code on AWS the cron triggering 2 times. Here is my code 
`var job2 = new CronJob('00 00 10 * * *', (res) => {
    woStatusCheck();
}, null, false, 'Asia/Kolkata');
job2.start();`

**Comment by intcreator** [comment] 2022-04-24 00:38
most likely there's something wrong with the way you deployed it. you sure the original job isn't still running? you sure you didn't run the script twice on AWS? deployment problems are probably out of scope for GitHub issues on this project, so unless you can point to a specific bug in the code causing the problem this issue should be closed

**Comment by intcreator** [comment] 2023-02-18 06:14
closing as stale/highly unlikely to be caused by the library

**Closed by intcreator** 2023-02-18 06:14 UTC
