### ISSUE TITLE
The job is repeated multiple times every 6 hours

### ISSUE THREAD

**Issue by xiaomoziyi** [kelektiv/node-cron#897] opened 2024-10-11 02:57 UTC
### Description

The job is repeated multiple times every 6 hours, my version is 2.4.4
![image](https://github.com/user-attachments/assets/3c67adf3-1681-4076-9bec-a4d3d5d99d7e)

### Expected Behavior

Should only be executed once

### Actual Behavior

Executed multiple times

### Steps to Reproduce

In my local area, I use vite-node to do global hot updates. I don’t know if this will have any impact.

### Context

This task will cause my task to be executed multiple times

### Your Environment

- **`cron` version**:
- **NodeJS version**:
- **Operating System and version**:
- **TypeScript version (if applicable)**:
- **Link to your project (if applicable)**:

**Comment by sheerlox** [comment] 2024-10-20 12:33
Hi, with so little information about your setup, we're going to have a hard time debugging the issue.

This is probably not a bug in our library but a misconfiguration issue on your side, whether in the code or the architecture.

That being said, we'd be glad to offer assistance if you could share more information.

**Comment by zeeshan7417** [comment] 2024-10-21 15:47
hey which file need to work can you tell me file name

**Comment by sheerlox** [comment] 2024-10-22 05:36
Closing this issue for now, feel free to re-open if you can share more information.

You might also want to consider joining [our Discord server](https://discord.com/invite/yyKns29zch) so we can provide support in a more casual form than on GitHub.

**Closed** 2024-10-24 01:56 UTC
Labels: support
